"""empty message

Revision ID: e7bd6a78abaa
Revises: 1dba70337673
Create Date: 2020-10-22 15:07:22.857515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7bd6a78abaa'
down_revision = '1dba70337673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'hacker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grades', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grades', 'hacker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
